export *  from './home.js'
export *  from './special.js'
export *  from './detail.js'
export *  from './cheap.js'
export *  from './my.js'
export *  from './seek.js'
export *  from './shopcar.js'
export *  from './tab.js'